name: ECHO

on:
  workflow_call:
    inputs:
      message:
        type: string
        description: Message
        default: 'JFokus 2023'
        required: false

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo ${{ inputs.message }}

  stepsi:
    runs-on: ubuntu-latest
    steps:
      - uses: ./tools/custom-actions/e2e/
